### ISSUE TITLE
有没有独立的，我想用swoole改，但是对Laravel不熟悉

### ISSUE THREAD

**Issue by ifdandy** [stingbo/mengine#1]
有没有独立的，我想用swoole改，但是对Laravel不熟悉

**Comment by stingbo** [comment]
没有基于Swoole的，以后可以考虑。其实这个库只有少部分依赖Laravel，就是其中的读取配置与触发事件部分，把读取config与触发event部分修改了，调试一下应该就可以了，PS:Laravel上手也快

**Comment by ifdandy** [comment]
好，我读一下代码试着改，laraval组件依赖之类太多，感觉和yii像，一直没接触过

**Comment by stingbo** [comment]
有问题可以交流

**Comment by stingbo** [comment]
> 好，我读一下代码试着改，laraval组件依赖之类太多，感觉和yii像，一直没接触过

 是的，他们很像，有问题随时问我，我写了一个go的独立的撮合服务，这样的话，PHP项目只需要调用rpc接口，把数据喂给go的服务了就行了
