### ISSUE TITLE
Services/MengineService.php的78行有问题

### ISSUE THREAD

**Issue by olives006** [stingbo/mengine#2]
if (!$this->isHashDeleted) {
            Redis::hdel($order->order_hash_key, $order->order_hash_field);
        }
应该是
if (!$this->isHashDeleted($order)) {
            Redis::hdel($order->order_hash_key, $order->order_hash_field);
        }
吧

**Comment by stingbo** [comment]
![image](https://user-images.githubusercontent.com/12377271/102580531-ae692600-4139-11eb-8618-c4eca14cce4f.png)

在一次优化的时候写错了，谢谢斧正
