### ISSUE TITLE
请问下是一个交易对一个队列服务吗？

### ISSUE THREAD

**Issue by ygcool** [stingbo/mengine#3]
比如示例中的：php artisan queue:work --queue=abc2usdt

业务中肯定是还有其他交易对，是不是就启动多个队列？
php artisan queue:work --queue=xx2xx
php artisan queue:work --queue=hh2hh

感谢回复。

**Comment by stingbo** [comment]
> 比如示例中的：php artisan queue:work --queue=abc2usdt
> 
> 业务中肯定是还有其他交易对，是不是就启动多个队列？
> php artisan queue:work --queue=xx2xx
> php artisan queue:work --queue=hh2hh
> 
> 感谢回复。

是的，多个交易对就使用多个队列，推荐使用 Laravel Horizon 管理队列，带有管理与监控队列的功能与面板
