### ISSUE TITLE
Hi, deleteOrder , Undefined variable: node

### ISSUE THREAD

**Issue by bill17665490461** [stingbo/mengine#4]
local.ERROR: Undefined variable: node {"exception":"[object] (ErrorException(code: 0): Undefined variable: node at /www/wwwroot/test.com/blog/vendor/sting_bo/mengine/src/Services/CommissionPoolService.php:53

**Comment by bill17665490461** [comment]
add before:
$link_service = new LinkService($order->node_link);
$node = $link_service->getNode($order->node);

**Comment by stingbo** [comment]
Well done :+1:
