### ISSUE TITLE
有这样的情况吗？

### ISSUE THREAD

**Issue by piaohan** [stingbo/mengine#5]
我自己这段时间也在做，用laravel原生写了一个撮合，挂单后进入队列撮合，但是我遇到一个问题，并发的情况如何保证队列一个顺序进，一个顺序消费？

**Comment by stingbo** [comment]
即使在高并发的情况下，入队列也是先来先进，入队列之后消费队列就是顺序的了。
这和秒杀抢购是一样的，或者你把进入队列之后的顺序看做下单的顺序呢
